version: '3.3'

services:
  pgadmin:
      image: dpage/pgadmin4
      container_name: pgadmin4_container
      restart: always

      environment:
        PGADMIN_DEFAULT_EMAIL: srv-admin@okbtsp.com
        PGADMIN_DEFAULT_PASSWORD: qwert1234
        PGADMIN_LISTEN_PORT: 80
      ports:
       - "15432:80"
  
  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379"  # Проксируйте порт Redis на хостовую машину