# Generated by Django 5.0.2 on 2024-11-05 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Leading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Specialist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Запрос', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Supler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=20, unique=True)),
                ('date', models.DateField()),
                ('article', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('unit', models.CharField(default='шт', max_length=50)),
                ('quantity', models.IntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comersant.comment')),
                ('leading', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comersant.leading')),
                ('specialist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comersant.specialist')),
                ('status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='comersant.status')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comersant.supler')),
            ],
        ),
    ]
