# Generated by Django 5.0.2 on 2024-11-11 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comersant', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Комментарий склада', 'verbose_name_plural': 'Комментарии склада'},
        ),
        migrations.AlterModelOptions(
            name='invoice',
            options={'verbose_name': 'Позиции в обработке', 'verbose_name_plural': 'Позиции в обработке'},
        ),
        migrations.AlterModelOptions(
            name='leading',
            options={'verbose_name': 'Ведущий', 'verbose_name_plural': 'Ведущие'},
        ),
        migrations.AlterModelOptions(
            name='specialist',
            options={'verbose_name': 'Специалист', 'verbose_name_plural': 'Специалисты'},
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name': 'Статус', 'verbose_name_plural': 'Статусы'},
        ),
        migrations.AlterModelOptions(
            name='supler',
            options={'verbose_name': 'Поставщик', 'verbose_name_plural': 'Поставщики'},
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.CharField(max_length=255, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='article',
            field=models.CharField(max_length=100, verbose_name='Артикул'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comersant.comment', verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='date',
            field=models.DateField(verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(max_length=20, verbose_name='Номер счета'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='leading',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comersant.leading', verbose_name='Руководитель'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='quantity',
            field=models.IntegerField(verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='specialist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comersant.specialist', verbose_name='Специалист'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='comersant.status', verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comersant.supler', verbose_name='Поставщик'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='unit',
            field=models.CharField(default='шт', max_length=50, verbose_name='Единица измерения'),
        ),
        migrations.AlterField(
            model_name='leading',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='specialist',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='status',
            name='name',
            field=models.CharField(default='Запрос', max_length=100, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='supler',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Имя'),
        ),
    ]
