# Generated by Django 5.0.2 on 2024-10-30 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comersant', '0002_comment_leading'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
