# Generated by Django 5.0.2 on 2024-12-16 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comersant', '0002_alter_comment_options_alter_invoice_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DescriptionProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Описание проблемы',
                'verbose_name_plural': 'Описание проблемы',
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='project',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Проект'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='quantity',
            field=models.FloatField(verbose_name='Количество'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='description_problem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='comersant.descriptionproblem', verbose_name='Описание проблемы'),
        ),
    ]
