# Generated by Django 5.0.2 on 2024-12-16 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comersant', '0003_descriptionproblem_invoice_project_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='description_problem',
            field=models.TextField(blank=True, null=True, verbose_name='Описание проблемы'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='comersant.status', verbose_name='Статус'),
        ),
        migrations.DeleteModel(
            name='DescriptionProblem',
        ),
    ]
