# Generated by Django 5.0.2 on 2024-10-30 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comersant', '0003_supler'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
