# Generated by Django 5.0.2 on 2024-10-30 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comersant', '0004_specialist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('article', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('unit', models.CharField(default='шт', max_length=50)),
                ('quantity', models.IntegerField()),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comersant.comment')),
                ('leading', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comersant.leading')),
                ('specialist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comersant.specialist')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comersant.supler')),
            ],
        ),
    ]
