# Generated by Django 5.0.2 on 2024-11-05 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comersant', '0006_status_invoice_description_invoice_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TableData',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
