# Generated by Django 5.0.2 on 2024-08-23 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RemainsInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.CharField(max_length=70, null=True)),
                ('title', models.TextField(null=True)),
                ('base_unit', models.CharField(max_length=10, null=True)),
            ],
        ),
    ]
