# Generated by Django 5.0.2 on 2024-08-26 11:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='remainsinventory',
            options={'verbose_name': 'Инвентаризация', 'verbose_name_plural': 'Инвентаризация'},
        ),
        migrations.AlterField(
            model_name='remainsinventory',
            name='article',
            field=models.CharField(max_length=70, null=True, verbose_name='Артикул'),
        ),
        migrations.AlterField(
            model_name='remainsinventory',
            name='base_unit',
            field=models.CharField(max_length=10, null=True, verbose_name='Единица'),
        ),
        migrations.AlterField(
            model_name='remainsinventory',
            name='title',
            field=models.TextField(null=True, verbose_name='Наименование'),
        ),
        migrations.CreateModel(
            name='OrderInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_ord', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.remainsinventory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
