# Generated by Django 5.0.2 on 2024-08-26 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_remainsinventory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='remainsinventory',
            name='status',
            field=models.CharField(blank=True, null=True, verbose_name='Статус'),
        ),
    ]
