# Generated by Django 5.0.2 on 2024-09-05 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_remainsinventory_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderinventory',
            options={'verbose_name': 'Детализация иннвентаризации', 'verbose_name_plural': 'Детализация иннвентаризации'},
        ),
    ]
