# Generated by Django 5.0.2 on 2024-09-10 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_orderinventory_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreationdDateInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Дата создания',
            },
        ),
    ]
