# Generated by Django 5.0.2 on 2024-09-10 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_creationddateinventory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='creationddateinventory',
            options={'verbose_name': 'Дата создания списка инвентаризации', 'verbose_name_plural': 'Дата создания списка инвентаризации'},
        ),
    ]
