# Generated by Django 5.0.2 on 2024-09-15 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data_Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_remains', models.IntegerField(default=1, null=True)),
                ('article', models.CharField(max_length=60, null=True)),
                ('party', models.CharField(max_length=20, null=True)),
                ('title', models.TextField(null=True)),
                ('base_unit', models.CharField(max_length=10, null=True)),
                ('comment', models.TextField(null=True)),
                ('date', models.DateTimeField(null=True)),
                ('address', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Deleted',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.TextField(null=True)),
                ('party', models.CharField(max_length=9, null=True)),
                ('title', models.TextField(null=True)),
                ('comment', models.TextField(null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('address', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Remains',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=50, null=True, verbose_name='Комментарий')),
                ('code', models.CharField(max_length=50, null=True, verbose_name='Код')),
                ('article', models.TextField(null=True, verbose_name='Артикул')),
                ('party', models.CharField(max_length=9, null=True, verbose_name='Партия')),
                ('title', models.TextField(null=True, verbose_name='Наименование')),
                ('base_unit', models.CharField(max_length=10, null=True, verbose_name='Единица')),
                ('project', models.CharField(max_length=30, null=True, verbose_name='Проект')),
                ('quantity', models.FloatField(blank=True, null=True, verbose_name='Количество')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Остаток',
                'verbose_name_plural': 'Остатки',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, null=True, verbose_name='Пользователь')),
                ('text', models.TextField(verbose_name='Отзыв')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.TextField(null=True)),
                ('party', models.CharField(max_length=9, null=True)),
                ('title', models.TextField(null=True)),
                ('comment', models.TextField(null=True)),
                ('date', models.DateTimeField(null=True)),
                ('address', models.CharField(max_length=100, null=True)),
                ('data_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finder.data_table')),
            ],
        ),
    ]
