# Generated by Django 5.0.2 on 2024-04-07 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data_Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_remains', models.IntegerField(default=1, null=True)),
                ('article', models.CharField(max_length=60, null=True)),
                ('party', models.CharField(max_length=20, null=True)),
                ('title', models.TextField(null=True)),
                ('base_unit', models.CharField(max_length=10, null=True)),
                ('comment', models.TextField(null=True)),
                ('date', models.DateTimeField(null=True)),
                ('address', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Deleted',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.TextField(null=True)),
                ('party', models.CharField(max_length=9, null=True)),
                ('title', models.TextField(null=True)),
                ('comment', models.TextField(null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('address', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Remains',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=50, null=True)),
                ('code', models.CharField(max_length=50, null=True)),
                ('article', models.TextField(null=True)),
                ('party', models.CharField(max_length=9, null=True)),
                ('title', models.TextField(null=True)),
                ('base_unit', models.CharField(max_length=10, null=True)),
                ('project', models.CharField(max_length=30, null=True)),
                ('quantity', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.TextField(null=True)),
                ('party', models.CharField(max_length=9, null=True)),
                ('title', models.TextField(null=True)),
                ('comment', models.TextField(null=True)),
                ('date', models.DateTimeField(null=True)),
                ('address', models.CharField(max_length=100, null=True)),
                ('data_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finder.data_table')),
            ],
        ),
    ]
