# Generated by Django 5.0.2 on 2024-03-15 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address_Prod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_cell', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Paty_Prod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Data_Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.CharField(max_length=50, null=True)),
                ('title', models.TextField(null=True)),
                ('base_unit', models.CharField(max_length=10, null=True)),
                ('comment', models.TextField(null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finder.address_prod')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finder.paty_prod')),
            ],
        ),
    ]
