# Generated by Django 5.0.2 on 2024-08-26 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='remains',
            options={'verbose_name': 'Остаток', 'verbose_name_plural': 'Остатки'},
        ),
        migrations.AlterField(
            model_name='remains',
            name='article',
            field=models.TextField(null=True, verbose_name='Артикул'),
        ),
        migrations.AlterField(
            model_name='remains',
            name='base_unit',
            field=models.CharField(max_length=10, null=True, verbose_name='Единица'),
        ),
        migrations.AlterField(
            model_name='remains',
            name='code',
            field=models.CharField(max_length=50, null=True, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='remains',
            name='comment',
            field=models.CharField(max_length=50, null=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='remains',
            name='party',
            field=models.CharField(max_length=9, null=True, verbose_name='Партия'),
        ),
        migrations.AlterField(
            model_name='remains',
            name='project',
            field=models.CharField(max_length=30, null=True, verbose_name='Проект'),
        ),
        migrations.AlterField(
            model_name='remains',
            name='quantity',
            field=models.FloatField(blank=True, null=True, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='remains',
            name='title',
            field=models.TextField(null=True, verbose_name='Наименование'),
        ),
    ]
