# Generated by Django 5.0.2 on 2024-03-19 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data_Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_remains', models.IntegerField()),
                ('article', models.CharField(max_length=50, null=True)),
                ('party', models.CharField(max_length=20, null=True)),
                ('title', models.TextField(null=True)),
                ('base_unit', models.CharField(max_length=10, null=True)),
                ('comment', models.TextField(null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('address', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
