# Generated by Django 5.0.2 on 2024-03-20 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0002_data_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_table',
            name='index_remains',
            field=models.IntegerField(null=True),
        ),
    ]
