# Generated by Django 5.0.2 on 2024-04-03 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0002_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='data_table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finder.data_table'),
        ),
    ]
