# Generated by Django 5.0.2 on 2024-04-04 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0003_alter_history_data_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='history',
            options={},
        ),
        migrations.AlterField(
            model_name='history',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
