# Generated by Django 5.0.2 on 2024-11-05 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0003_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='remains',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
