# Generated by Django 5.0.2 on 2024-03-20 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0003_alter_data_table_index_remains'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_table',
            name='index_remains',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
