# Generated by Django 5.0.2 on 2024-10-23 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0003_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='remains',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
