# Generated by Django 5.0.2 on 2024-04-04 23:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0004_alter_history_options_alter_history_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20, verbose_name='Тип')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='Standart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('din', models.CharField(max_length=20, verbose_name='ДИН')),
                ('gost', models.CharField(max_length=20, verbose_name='ГОСТ')),
                ('iso', models.CharField(max_length=20, verbose_name='ISO')),
                ('another', models.CharField(max_length=20, verbose_name='Другое')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finder.metiz')),
            ],
        ),
    ]
