# Generated by Django 5.0.2 on 2024-03-21 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0004_alter_data_table_index_remains'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remains',
            name='article',
            field=models.TextField(null=True),
        ),
    ]
