# Generated by Django 5.0.2 on 2024-04-04 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0005_metiz_standart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Noname',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.ManyToManyField(to='finder.standart')),
            ],
        ),
    ]
