# Generated by Django 5.0.2 on 2024-04-04 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0006_noname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metiz',
            name='type',
        ),
        migrations.RemoveField(
            model_name='standart',
            name='type',
        ),
        migrations.AddField(
            model_name='metiz',
            name='standards',
            field=models.ManyToManyField(to='finder.standart'),
        ),
        migrations.AlterField(
            model_name='metiz',
            name='description',
            field=models.TextField(),
        ),
        migrations.DeleteModel(
            name='Noname',
        ),
    ]
